name: Publish Ruby
'on':
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v7
        with:
          ref: main
      - uses: ./.github/actions/publish-ruby-action
        env:
          RUBYGEMS_TOKEN: $\{{ secrets.{{github_token_prefix}}_RUBYGEMS_TOKEN }}
